---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cluster-credentials
  namespace: default
spec:
  encryptedData:
    clouds.yaml: AgBOLK+hCS93tF2KVnFYY2Ruvr0BUMSuTUGICkyDIHLu9Z3Qo2uoOawgPa7M55ENCfN7DhdFtMcL+oYcBbLXyBwBjkluuuGiGcvkRu4WKkLbYAmDeaJ/G5h1rPiWRJjhOM6zazid3Voncepe2+su8dTVJuwFi8uNVqjNyCYhpmvafvJDtbqG91zwBVRJE4OC2impCDXeKYMFEJwsU2/A/lQ6mYxLYP6GAIs2/OupQ0zt0IIRS4NbcYx8InASPS3PhZjJkYnbUb+hBhWBrWIRvgvAjP80k6I/nyeg3qIqu95TSQ7N4rFWSUnfj7Y+LNxK/pF1gCOixhD8GJiZ8K7WVMJmELY4lg+xzXbHjZpZ5SyvbcPUwGzFhnpcX4cdshpaGOV/Htt3+ichBPPtUkIuvrVACS2BkHXftoCR21J26C6+jnT/n9VhxerdYU46eMRFOsizomhrUP/G3D+cGE+Qyx3Z2wD6bp7OoA5f9yOeAWL2MUEwms5Q7dXBUZhdb35/R+mb1wGRDNsSUAZkr5R6c9pUKnLDkh2enoO7SqFBLpizAw/bx3kG/iWZ/WAi6mjzX22LOFSgZvpbYH12ySaz85Be7DRhdufpZxwierYNOVm1F2OW+f8risfXGFChz2hIwR2jXc9F710rUBR/eFDLUK+uVtazClMWhfV7KCzpuWQzgz3ykOEJtIqo67j7pkY1J24IePziYZ+oYYBjLhme5N48wfBbfFuOigHnvwlVmWDvwbCgxEcBTMBaS1C47w68KG/3ulWVVIo8y08CBiKnvtKMZNGX6unfdfyRh6S9d2WVPkP1/834WlrYq15RiLYtPt9X6hghpqqKBwu+IHhGe9UxW78TTInrWNCi618d9dBUwQoXC2BhLMSgWBe5yjBPJmdC9wHLo8MDJrCkC3SGKweRNtWLQKKKfSEqnKpJ7IMjaZy6POQEbhCofMUXlDC7Jv4gryK6/9Yk8DwU1ROL9rpeST8B+eAe7iAbAYZ3TCtv1hl1149Ac7+nBazsh5XS9c2OoA5IO44TxSKAk0w+6u57ok38Y3dr+0C0Nz00ePJp8++1yzZVpXhxLXVeYEy1jrRBfVnfYn0YzBiG/CuSYpkgvVxBHP5UkmSwOYrQTPh7PRkM3qf84MCjh0tAtpk0PjELMv0uObkySQjLsSvFfgyRzhfK0FtIUzVJSSrVisxghEiW96mRuVM1dKh1WYJsCmYFuW0y2Ge91NsX2FKjPilJZ6nI
  template:
    metadata:
      labels:
        addons.stackhpc.com/watch: "true"
      name: cluster-credentials
      namespace: default
