# Example secret prior to kubeseal. The secret must be sealed using
# the target CAPI management cluster's kubeconfig file using:
#
# kubeseal \
#   --format yaml \
#   --controller-name sealed-secrets \
#   --controller-namespace sealed-secrets-system \
#   --secret-file credentials.yml \
#   --sealed-secret-file credentials.yml \
#   -n <target-namespace>
#
# where <target-namespace> must match spec.targetNamespace of the
# Kustomization resource on the CAPI management cluster.
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-credentials
  labels:
    # Tell the cluster-api-addon-provider to watch this resource for
    # changes and update any Manifest or HelmRelease addon resources
    # which refer to it whenever this secret is changed / rotated.
    addons.stackhpc.com/watch: "true"
stringData:
  clouds.yaml: |
    clouds:
      openstack:
        auth:
          auth_url: "<auth url>"
          application_credential_id: "<app cred id>"
          application_credential_secret: "<app cred secret>"
          project_id: "<project id>"
        region_name: "<region name>"
        interface: "public"
        identity_api_version: 3
        auth_type: "v3applicationcredential"
